import numpy as np

def exp_rand(scale: float = 1.0) -> float: ...
def exp_rands(n: int, scale: float = 1.0) -> np.ndarray: ...
def uniform_rand(low: float = 0.0, high: float = 1.0) -> float: ...
def uniform_rands(n: int, low: float = 0.0, high: float = 1.0) -> np.ndarray: ...
def normal_rand(mu: float = 0.0, sigma: float = 1.0) -> float: ...
def normal_rands(n: int, mu: float = 0.0, sigma: float = 1.0) -> np.ndarray: ...
