name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # 或者你的默认分支名
    paths:
      - 'docs/**'  # 只有当 docs 文件夹中的文件发生变化时才触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 这里可以添加构建步骤,如果需要的话
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/rust/diffusionx  # 指定要发布的目录
